import os

env = Environment()

full_path = os.path.realpath(".")
path, cwd = os.path.split(full_path)

# Set the target executable.  
#
#target = 'App'
target = cwd

# CCFLAGS : general C and C++ flags
env.Append( CCFLAGS = [
    '-Wall',
    '-Wextra',
    '-std=c++14',
    ] )

env.Program( target=target, source=Glob('*.cpp'))